# Generated by Django 5.2 on 2025-04-13 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(max_length=15)),
                ('receivables', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unused_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_available', models.IntegerField()),
                ('new_quantity_on_hand', models.IntegerField()),
                ('quantity_adjusted', models.IntegerField()),
                ('account', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, default='default_value', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_remarks', models.TextField()),
                ('unit', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('sales_order', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('carrier', models.CharField(max_length=100, null=True)),
                ('shipping_date', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='Not Shipped', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasehogyi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=50, unique=True)),
                ('reference_no', models.CharField(max_length=50, null=True)),
                ('vendor', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=50, unique=True)),
                ('reference_no', models.CharField(max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('received', 'Received'), ('paid', 'Paid')], default='pending', max_length=50)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('work_phone', models.IntegerField()),
                ('receivables', models.IntegerField()),
                ('unused_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopSellingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_sold', models.IntegerField()),
                ('image_url', models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWK9GUpJGn7l4a9yq31T085a5DtpdnBQ-KCw&s', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('vendor_display_name', models.CharField(max_length=100, null=True)),
                ('vendor_email', models.EmailField(max_length=100, unique=True)),
                ('work_phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_remarks', models.CharField(max_length=80)),
                ('item_colour', models.CharField(max_length=20)),
                ('item_size', models.CharField(max_length=10)),
                ('purchase_rate', models.FloatField()),
                ('sales_rate', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('reference_number', models.CharField(max_length=30)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.items')),
                ('purchase_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.purchasereceive')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(max_length=20)),
                ('reference_no', models.CharField(max_length=20)),
                ('order_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=20)),
                ('shipment_status', models.CharField(choices=[('not_shipped', 'Not Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor'),
        ),
    ]
