# Generated by Django 5.2 on 2025-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor',
            new_name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
