# Generated by Django 5.2 on 2025-04-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_vendor_purchaseorder_vendor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
