# Generated by Django 5.2 on 2025-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
