# Generated by Django 5.2 on 2025-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackart', '0003_wishlistitem_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('offer_price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
