# Generated by Django 5.1.7 on 2025-04-14 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackart', '0005_delete_cartitem_delete_product_delete_wishlistitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='chooser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
