# Generated by Django 5.1.7 on 2025-04-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackart', '0006_alter_products_chooser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
