# Generated by Django 5.1.7 on 2025-04-14 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trackart', '0008_products_in_wishlist_alter_products_image_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='in_wishlist',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('image_link', models.URLField()),
                ('description', models.TextField()),
                ('offer_price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('chooser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
